#!/.runcvm/guest/bin/bash

from_bin() {
  tr '\200\201\202\203\204\205' "\011\012\040\047\042\134"
}

error() {
  echo "OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd (\"$cwd\") set in config.json failed: no such file or directory: unknown"
  exit 126
}

uidgid="$1"
cwd_bin="$2"
shift 2

IFS=':' read -r uid gid additionalGids <<< "$uidgid"

args_bin="$1"
env_bin="$2"

mapfile -t args < <(echo -n "$args_bin" | from_bin)
mapfile -t env < <(echo -n "$env_bin" | from_bin)
cwd=$(echo -n "$cwd_bin" | from_bin)

cd "$cwd" 2>/dev/null && unset OLDPWD || error

# Load original environment
. /.runcvm/config

# Load defaults and aliases
. $RUNCVM_GUEST/scripts/runcvm-ctr-defaults

# Ensure guest tools are in PATH for the executed command
found_path=0
for i in "${!env[@]}"; do
  if [[ "${env[$i]}" == PATH=* ]]; then
    env[$i]="PATH=$RUNCVM_PATH:${env[$i]#PATH=}"
    found_path=1
    break
  fi
done
if [ "$found_path" -eq 0 ]; then
  env+=("PATH=$RUNCVM_PATH")
fi

exec -c /.runcvm/guest/lib/ld $RUNCVM_GUEST/bin/busybox env -i "${env[@]}" /.runcvm/guest/lib/ld $RUNCVM_GUEST/bin/s6-applyuidgid -u $uid -g $gid -G "$additionalGids" "${args[@]}"